name: action-itemplate-ghpages
author: Itamar Carvalho
description: Action to publish auto-filled GitHub Pages with a pre-build theme or a custom template.
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  templates_folder:
    description: "The relative path to the folder that contains your site's templates or the chosen theme id."
    required: true
    default: 'templates'
  allow_templates_subfolders:
    description: "Allow the templates to be stored in subfolders under templates_folder ('true'/'false')."
    required: false
    default: 'false'
  pages_branch:
    description: "Branch name for storing github pages"
    required: true
    default: 'gh-pages'
  pages_folder:
    description: "Name of the output folder where generated html will be stored."
    required: true
    default: 'docs'
  snippets_folder:
    description: "The relative path to the folder that contains your site's snippets, if any"
    required: false
    default: 'snippets'
  timezone: 
    description: "Time zone to calculate the update time"
    required: true
    # (default: America/Sao_Paulo, which is GMT-3 - sorry, I'm brazilian =) )
    default: 'America/Sao_Paulo'
  max_issues:
    description: "The max number of issues that will be retrieved and shown (0-100)."
    required: false
    default: '5'
  max_collaborators:
    description: "The max number of collaborators that will be retrieved and shown (0-100)."
    required: false
    default: '20'
  publish_readme_md:
    description: "Publish the README.md from the repository root in the generated page. True makes it become README.html while 'inline' will make it available as a snippet 'SNP_README' and put inline if using a theme. ('false'/'true'/'inline')"
    required: false
    default: 'false'
  content_to_copy:
    description: "Folders or files to copy when publishing, keeping the relative path, separated by commas."
    required: false
    default: ''
  convert_md_to_html:
    description: "Convert Markdown files pointed by 'content_to_copy' to HTML, changing also the links to them."
    required: false
    default: 'false'
  syntax_highlight_enable:
    description: "Enable syntax highlight of code tags with class 'language-*', like some markdown converted files."
    required: false
    default: 'false'
  syntax_highlight_theme:
    description: "Syntax highlight theme from Prism.js"
    required: false
    default: 'default'
  log_level:
    description: "The log level, according to the ones defined in java.util.logging.Level."
    required: false
    default: 'WARNING'
runs:
  using: 'docker'
  image: 'Dockerfile'
